esphome:
  name: "smart-touch-1"
  friendly_name: Smart Touch Lamp 1
  compile_process_limit: 1

esp32:
  board: esp32doit-devkit-v1
  # board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: info
#  level: debug # use this when using setup_mode for esp32_touch

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # manual_ip:
  #   static_ip: xxx.xxx.xxx.xxx
  #   gateway: xxx.xxx.xxx.xxx
  #   subnet: xxx.xxx.xxx.xxx

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "FR-Lamp-Touch"
    password: !secret wifi_password

# Enable Web server.
web_server:
  port: 80
  
captive_portal:


esp32_touch:
  setup_mode: false
  # Use a longer measurement duration for classic ESP32 (S1/S0) modules
  # This improves stability on older chips compared to shorter durations
  # measurement_duration: 3ms # use for s1/s0 chips
  # measurement_duration: 0.25ms # use for s2/s3 chips
  
binary_sensor:
  - platform: esp32_touch
    name: "Touch Pad Pin 13"
    pin: GPIO13
    # Starting threshold suitable for ESP32 (non-S2/S3) boards. Tune as needed.
    threshold: 700
    # filters:
    #   # Small filter, to debounce the spurious events.
    #   - delayed_on: 10ms
    #   - delayed_off: 10ms
    #on_press:
    on_click:
    - min_length: 10ms
      max_length: 500ms
      # Short touch to cycle through brightnesses
      then:
        - number.increment:
            id: dimmer_control
            cycle: true

number:     
  - platform: template
    name: Dimmer Control
    id: dimmer_control
    min_value: 0
    max_value: 100
    step: 25
    optimistic: true
    set_action:
      then:
        - light.turn_on:
            id: dimmer
            brightness: !lambda 'return x / 100.0;'

# restart-button
button:
  - platform: restart
    name: "restart-esp32-dim-touch"

# AC Dimmer Configuration
light:
  - platform: monochromatic
    id: dimmer
    name: "Smart Lamp"
    output: ac_dimmer_output
    # restore_mode: ALWAYS_ON

output:
  - platform: ac_dimmer
    id: ac_dimmer_output
    gate_pin: GPIO25  # Gate pin for controlling the dimmer
    zero_cross_pin:
      number: GPIO18  # Zero-cross pin for synchronization
      mode:
        input: True
        pullup: True
      inverted: yes
