esphome:
  name: "smart-touch-1-dimmerlink"
  friendly_name: Smart Touch Lamp 1 DimmerLink

esp32:
  board: esp32doit-devkit-v1
  # board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: info
#  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "FR-Lamp-Touch"
    password: !secret wifi_password

# Enable Web server.
web_server:
  port: 80

captive_portal:

esp32_touch:
  setup_mode: false
  measurement_duration: 0.25ms

# UART interface for DimmerLink board
# DimmerLink connects via UART at 115200 baud
uart:
  - id: dimmerlink_uart
    tx_pin: GPIO17  # TX pin for DimmerLink (adjust if needed)
    rx_pin: GPIO16  # RX pin for DimmerLink (adjust if needed)
    baud_rate: 115200
    data_bits: 8
    stop_bits: 1
    parity: NONE

binary_sensor:
  - platform: esp32_touch
    name: "Touch Pad Pin 13"
    pin: GPIO13
    threshold: 550000
    filters:
      # Small filter, to debounce the spurious events.
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_click:
    - min_length: 10ms
      max_length: 500ms
      # Short touch to cycle through brightnesses
      then:
        - number.increment:
            id: dimmer_control
            cycle: true

number:
  - platform: template
    name: Dimmer Control
    id: dimmer_control
    min_value: 0
    max_value: 100
    step: 25
    optimistic: true
    set_action:
      then:
        - uart.write:
            id: dimmerlink_uart
            # DimmerLink UART command format: [0x02, 0x53, dimmer_id, brightness]
            # 0x02 = SET command
            # 0x53 = Brightness/SET command identifier
            # 0x00 = dimmer ID (0)
            # last byte = brightness value (0-100)
            data: !lambda
              - return {0x02, 0x53, 0x00, (uint8_t)x};

# restart-button
button:
  - platform: restart
    name: "restart-esp32-dimmerlink-touch"

# DimmerLink Light Configuration
light:
  - platform: monochromatic
    id: dimmer
    name: "Smart Lamp"
    output: dimmerlink_output
    restore_mode: ALWAYS_ON

output:
  - platform: template
    id: dimmerlink_output
    type: float
    write_action:
      then:
        - uart.write:
            id: dimmerlink_uart
            # Convert brightness (0.0-1.0) to percentage (0-100)
            data: !lambda
              - uint8_t brightness = (uint8_t)(x * 100.0);
              - return {0x02, 0x53, 0x00, brightness};
